import CountriesListItem from 'components/CountriesListItem/CountriesListItem';
import { StyledList } from './List.styles';

export default function List() {
  return (
    <StyledList>
      <CountriesListItem
        countryFlag='https://disease.sh/assets/img/flags/af.png'
        countryName='Afghanistan'
        numberOfCases={123456}
      />
      <CountriesListItem
        countryFlag='https://disease.sh/assets/img/flags/af.png'
        countryName='Afghanistan'
        numberOfCases={123456}
      />
      <CountriesListItem
        countryFlag='https://disease.sh/assets/img/flags/af.png'
        countryName='Afghanistan'
        numberOfCases={123456}
      />
      <CountriesListItem
        countryFlag='https://disease.sh/assets/img/flags/af.png'
        countryName='Afghanistan'
        numberOfCases={123456}
      />
      <CountriesListItem
        countryFlag='https://disease.sh/assets/img/flags/af.png'
        countryName='Afghanistan'
        numberOfCases={123456}
      />
      <CountriesListItem
        countryFlag='https://disease.sh/assets/img/flags/af.png'
        countryName='Afghanistan'
        numberOfCases={123456}
      />
      <CountriesListItem
        countryFlag='https://disease.sh/assets/img/flags/af.png'
        countryName='Afghanistan'
        numberOfCases={123456}
      />
      <CountriesListItem
        countryFlag='https://disease.sh/assets/img/flags/af.png'
        countryName='Afghanistan'
        numberOfCases={123456}
      />
      <CountriesListItem
        countryFlag='https://disease.sh/assets/img/flags/af.png'
        countryName='Afghanistan'
        numberOfCases={123456}
      />
      <CountriesListItem
        countryFlag='https://disease.sh/assets/img/flags/af.png'
        countryName='Afghanistan'
        numberOfCases={123456}
      />
      <CountriesListItem
        countryFlag='https://disease.sh/assets/img/flags/af.png'
        countryName='Afghanistan'
        numberOfCases={123456}
      />
      <CountriesListItem
        countryFlag='https://disease.sh/assets/img/flags/af.png'
        countryName='Afghanistan'
        numberOfCases={123456}
      />
    </StyledList>
  );
}
